-- Cities table --

CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

USE hbtn_0d_usa;

CREATE TABLE IF NOt EXISTS cities(
	id		INT UNIQUE AUTO_INCREMENT PRIMARY KEY,
	state_id	INT FOREIGN KEY,
	name		VARCHAR(256)
)
